-- -----------------------------------------------------
-- Table `EMQX_CONNECTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS EMQX_CONNECTION (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CLIENT_ID VARCHAR(300) NOT NULL,
    CLIENT_TYPE VARCHAR(300) NOT NULL,
    CLIENT_ID VARCHAR(300) NOT NULL,
    ACCESS_TOKEN VARCHAR(100) NOT NULL,
    SCOPES CLOB,
    TENANT_ID INTEGER,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);