-- -----------------------------------------------------
-- Table `EMQX_CONNECTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS EMQX_CONNECTION (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DEVICE_ID VARCHAR(300) NOT NULL,
    DEVICE_TYPE VARCHAR(300) NOT NULL,
    CLIENT_ID VARCHAR(300) NOT NULL,
    ACCESS_TOKEN VARCHAR(100) NOT NULL,
    SCOPES TEXT,
    TENANT_ID INT,
    CREATED_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
