
-- -----------------------------------------------------
-- Table `AD_DEVICE`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `AD_DEVICE` (
  `DEVICE_ID` VARCHAR(45) NOT NULL,
  `FCM_TOKEN` VARCHAR(1000) NULL DEFAULT NULL,
  `DEVICE_INFO` VARCHAR(8000) NULL DEFAULT NULL,
  `IMEI` VARCHAR(45) NULL DEFAULT NULL,
  `IMSI` VARCHAR(45) NULL DEFAULT NULL,
  `OS_VERSION` VARCHAR(45) NULL DEFAULT NULL,
  `DEVICE_MODEL` VARCHAR(45) NULL DEFAULT NULL,
  `VENDOR` VARCHAR(45) NULL DEFAULT NULL,
  `LATITUDE` VARCHAR(45) NULL DEFAULT NULL,
  `LONGITUDE` VARCHAR(45) NULL DEFAULT NULL,
  `SERIAL` VARCHAR(45) NULL DEFAULT NULL,
  `MAC_ADDRESS` VARCHAR(45) NULL DEFAULT NULL,
  `DEVICE_NAME` VARCHAR(100) NULL DEFAULT NULL,
  `OS_BUILD_DATE` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`DEVICE_ID`));

-- -----------------------------------------------------
-- Table `AD_FEATURE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AD_FEATURE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CODE` VARCHAR(45) NOT NULL,
  `NAME` VARCHAR(100) NULL,
  `TYPE` VARCHAR(20) NULL,
  `HIDDEN` BOOLEAN DEFAULT FALSE,
  `DESCRIPTION` VARCHAR(200) NULL,
  PRIMARY KEY (`ID`));

-- -----------------------------------------------------
-- Table `AD_ENTERPRISE_USER_DEVICE`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `AD_ENTERPRISE_USER_DEVICE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ENTERPRISE_ID` VARCHAR(50) NULL,
  `EMM_USERNAME` VARCHAR(100) NOT NULL,
  `GOOGLE_USER_ID` VARCHAR(50) NULL,
  `ANDROID_PLAY_DEVICE_ID` VARCHAR(50) NULL,
  `EMM_DEVICE_ID` VARCHAR(50) NULL,
  `TENANT_ID` INT(11) NULL DEFAULT '0',
  `LAST_UPDATED_TIMESTAMP` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID`));

-- -----------------------------------------------------
-- Table `AD_ENTERPRISE_MANAGED_CONFIGS`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `AD_ENTERPRISE_MANAGED_CONFIGS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `MCM_ID` VARCHAR(50) NULL,
  `PROFILE_NAME` VARCHAR(100) NULL,
  `PACKAGE_NAME` VARCHAR(100) NOT NULL,
  `TENANT_ID` INT(11) NULL DEFAULT '0',
  `LAST_UPDATED_TIMESTAMP` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID`));

