-- -----------------------------------------------------
-- Table `AD_DEVICE`
-- -----------------------------------------------------
IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[AD_DEVICE]') AND TYPE IN (N'U'))
CREATE  TABLE AD_DEVICE (
  DEVICE_ID VARCHAR(45) NOT NULL,
  FCM_TOKEN VARCHAR(1000) NULL DEFAULT NULL,
  DEVICE_INFO VARCHAR(8000) NULL DEFAULT NULL,
  IMEI VARCHAR(45) NULL DEFAULT NULL,
  IMSI VARCHAR(45) NULL DEFAULT NULL,
  OS_VERSION VARCHAR(45) NULL DEFAULT NULL,
  DEVICE_MODEL VARCHAR(45) NULL DEFAULT NULL,
  VENDOR VARCHAR(45) NULL DEFAULT NULL,
  LATITUDE VARCHAR(45) NULL DEFAULT NULL,
  LONGITUDE VARCHAR(45) NULL DEFAULT NULL,
  SERIAL VARCHAR(45) NULL DEFAULT NULL,
  MAC_ADDRESS VARCHAR(45) NULL DEFAULT NULL,
  DEVICE_NAME VARCHAR(100) NULL DEFAULT NULL,
  OS_BUILD_DATE VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (DEVICE_ID));

-- -----------------------------------------------------
-- Table `AD_FEATURE`
-- -----------------------------------------------------
IF NOT  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[AD_FEATURE]') AND TYPE IN (N'U'))
CREATE TABLE AD_FEATURE (
  ID INT NOT NULL IDENTITY,
  CODE VARCHAR(45) NOT NULL,
  NAME VARCHAR(100) NULL,
  TYPE VARCHAR(20) NULL,
  HIDDEN BIT DEFAULT 0,
  DESCRIPTION VARCHAR(200) NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE AD_ENTERPRISE_USER_DEVICE (
  [ID] INT NOT NULL IDENTITY,
  [ENTERPRISE_ID] VARCHAR(50) NULL,
  [EMM_USERNAME] VARCHAR(100) NOT NULL,
  [GOOGLE_USER_ID] VARCHAR(50) NULL,
  [ANDROID_PLAY_DEVICE_ID] VARCHAR(50) NULL,
  [EMM_DEVICE_ID] VARCHAR(50) NULL,
  [TENANT_ID] INT NULL DEFAULT '0',
  [LAST_UPDATED_TIMESTAMP] DATETIME2(0) NOT NULL,
  PRIMARY KEY ([ID])
);

CREATE TABLE AD_ENTERPRISE_MANAGED_CONFIGS (
  [ID] INT NOT NULL IDENTITY,
  [MCM_ID] VARCHAR(50) NULL,
  [PROFILE_NAME] VARCHAR(100) NULL,
  [PACKAGE_NAME] VARCHAR(100) NOT NULL,
  [TENANT_ID] INT NULL DEFAULT '0',
  [LAST_UPDATED_TIMESTAMP] DATETIME2(0) NOT NULL,
  PRIMARY KEY ([ID])
) ;
