-- -----------------------------------------------------
-- Table `AD_DEVICE`
-- -----------------------------------------------------
CREATE TABLE AD_DEVICE (
  DEVICE_ID VARCHAR(45) NOT NULL ,
  DEVICE_INFO VARCHAR(4000) DEFAULT NULL,
  FCM_TOKEN VARCHAR(1000) DEFAULT NULL,
  IMEI VARCHAR(45) DEFAULT NULL,
  IMSI VARCHAR(45) DEFAULT NULL,
  OS_VERSION VARCHAR(45) DEFAULT NULL,
  DEVICE_MODEL VARCHAR(45) DEFAULT NULL,
  VENDOR VARCHAR(45) DEFAULT NULL,
  LATITUDE VARCHAR(45) DEFAULT NULL,
  LONGITUDE VARCHAR(45) DEFAULT NULL,
  SERIAL VARCHAR(45) DEFAULT NULL,
  MAC_ADDRESS VARCHAR(45) DEFAULT NULL,
  DEVICE_NAME VARCHAR(100) DEFAULT NULL,
  OS_BUILD_DATE VARCHAR(100) DEFAULT NULL,
  CONSTRAINT PK_AD_DEVICE PRIMARY KEY (DEVICE_ID)
)
/

-- -----------------------------------------------------
-- Table `AD_FEATURE`
-- -----------------------------------------------------
CREATE TABLE AD_FEATURE (
  ID INT NOT NULL,
  CODE VARCHAR(45) NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  TYPE VARCHAR(20) NULL,
  HIDDEN BIT DEFAULT 0,
  DESCRIPTION VARCHAR(200) DEFAULT NULL,
  CONSTRAINT AD_FEATURE PRIMARY KEY (ID)
)
/

-- -----------------------------------------------------
-- Sequence `AD_FEATURE_ID_INC_SEQ`
-- -----------------------------------------------------
CREATE SEQUENCE AD_FEATURE_ID_INC_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/
-- -----------------------------------------------------
-- Trigger `AD_FEATURE_ID_INC_TRIG`
-- -----------------------------------------------------
CREATE OR REPLACE TRIGGER AD_FEATURE_ID_INC_TRIG
BEFORE INSERT
ON AD_FEATURE
REFERENCING NEW AS NEW
FOR EACH ROW
  BEGIN
    SELECT AD_FEATURE_ID_INC_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
  END;
/


CREATE TABLE AD_ENTERPRISE_USER_DEVICE (
  ID NUMBER(10) NOT NULL,
  ENTERPRISE_ID VARCHAR2(50) NULL,
  EMM_USERNAME VARCHAR2(100) NOT NULL,
  GOOGLE_USER_ID VARCHAR2(50) NULL,
  ANDROID_PLAY_DEVICE_ID VARCHAR2(50) NULL,
  EMM_DEVICE_ID VARCHAR2(50) NULL,
  TENANT_ID NUMBER(10) DEFAULT '0' NULL,
  LAST_UPDATED_TIMESTAMP TIMESTAMP(0) NOT NULL,
  PRIMARY KEY (ID)
);

-- Generate ID using sequence and trigger
CREATE SEQUENCE AD_ENTERPRISE_USER_DEVICE_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER AD_ENTERPRISE_USER_DEVICE_seq_tr
 BEFORE INSERT ON AD_ENTERPRISE_USER_DEVICE FOR EACH ROW
 WHEN (NEW.ID IS NULL)
BEGIN
 SELECT AD_ENTERPRISE_USER_DEVICE_seq.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

CREATE TABLE AD_ENTERPRISE_MANAGED_CONFIGS (
  ID NUMBER(10) NOT NULL,
  MCM_ID VARCHAR2(50) NULL,
  PROFILE_NAME VARCHAR2(100) NULL,
  PACKAGE_NAME VARCHAR2(100) NOT NULL,
  TENANT_ID NUMBER(10) DEFAULT '0' NULL,
  LAST_UPDATED_TIMESTAMP TIMESTAMP(0) NOT NULL,
  PRIMARY KEY (ID)
) ;

-- Generate ID using sequence and trigger
CREATE SEQUENCE AD_ENTERPRISE_MANAGED_CONFIGS_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER AD_ENTERPRISE_MANAGED_CONFIGS_seq_tr
 BEFORE INSERT ON AD_ENTERPRISE_MANAGED_CONFIGS FOR EACH ROW
 WHEN (NEW.ID IS NULL)
BEGIN
 SELECT AD_ENTERPRISE_MANAGED_CONFIGS_seq.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/